# Generated by Django 3.2.3 on 2021-06-21 12:01

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('E:/Devfiles/Blossom/blossom_api/static'))),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('bio', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('plants', models.ManyToManyField(blank=True, to='api.Plant')),
            ],
        ),
    ]
