# Generated by Django 3.2.3 on 2021-06-22 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('E:/Devfiles/Blossom/blossom_api/media'))),
                ('category', models.CharField(choices=[('HERB', 'Herb'), ('SHRUB', 'Shrub'), ('TREE', 'Tree'), ('CLIMBER', 'Climber'), ('CREEPER', 'Creeper')], default='HERB', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('bio', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('pat', models.CharField(default='c04c4a49c663a208f25b785502678574dc862a0f6addac01c2b88ee953cc2907', max_length=64)),
                ('plants', models.ManyToManyField(blank=True, to='api.Plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
