# Generated by Django 3.2.3 on 2021-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=200)),
                ('request_ip', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('logging_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
